### ISSUE TITLE
Метод containsGame не находит игру

### ISSUE THREAD

**Issue by Gala05** [Gala05/Team-Project_Game-activity-tracking-#1]
### Описание
При тестировании метод containsGame в классе GameStore не находит игру

### Локация дефекта
https://github.com/Gala05/Team-Project_Game-activity-tracking-/blob/a1dc3ef0cb25a4a23fba25a801ead598c80d6fa0/src/main/java/ru/netology/GameStore.java#L32-L39

### Шаги воспроизведения
1. Открыть код программы в Idea,
2. Через метод publishGame добавить игру в каталог.
3. Вызвать метод containsGame
4. Запустить тест
5. Посмотреть на вывод в консоли

### Скриншот
![скрин](https://monosnap.com/image/AX229baeqTJaBFNlzP7s9a8mw4Ec98)

### Окружение
Операционная система: Windows 10
IDE: IntelliJ IDEA 2022.3.1 (Community Edition)
Java: OpenJDK 11

**Comment by AnaIvy** [comment]
**Fixed** with a commit **"Fix commit"**

**Comment by AnaIvy** [comment]
**Fixed** with a commit **"Fix commit"**
