### ISSUE TITLE
В методе getMostPlayer отсчет времени начинается не с нуля

### ISSUE THREAD

**Issue by Gala05** [Gala05/Team-Project_Game-activity-tracking-#2]
### Описание
В методе getMostPlayer в классе GameStore отсчет времени начинается не с нуля, поэтому при тесте при выставлении нулевого значения одному из игроков тест возвращает ошибку

### Локация дефекта
https://github.com/Gala05/Team-Project_Game-activity-tracking-/blob/a1dc3ef0cb25a4a23fba25a801ead598c80d6fa0/src/main/java/ru/netology/GameStore.java#L59
 
### Шаги воспроизведения
1. Открыть код программы в Idea,
2. Создаем тест, в котором есть 2 игрока и каталог игр.
3. Через метод addPlayTime добавить каждому игроку его игровое время.
4. Через метод getMostPlayer найти игрока, который который играл в игры этого каталога больше всего времени
5. Запустить тест
6. Посмотреть на вывод в консоли

### Скриншот
![скрин](https://monosnap.com/image/VelYTt8CcLcIbnVl6DOBdoHT8j6DUS)

### Окружение
Операционная система: Windows 10
IDE: IntelliJ IDEA 2022.3.1 (Community Edition)
Java: OpenJDK 11

**Comment by AnaIvy** [comment]
**Fixed** with a commit **"Fix commit"**
