### ISSUE TITLE
Метод shouldGetSumPlayerTime не суммирует общее количество времени

### ISSUE THREAD

**Issue by Gala05** [Gala05/Team-Project_Game-activity-tracking-#3]
### Описание
Метод shouldGetSumPlayerTime в классе GameStore не суммирует общее количество времени всех игроков, проведённого за играми этого каталога

### Локация дефекта

https://github.com/Gala05/Team-Project_Game-activity-tracking-/blob/a1dc3ef0cb25a4a23fba25a801ead598c80d6fa0/src/main/java/ru/netology/GameStore.java#L75-L77

### Шаги воспроизведения
1. Открыть код программы в Idea,
2. Создаем тест, в котором есть игрок и каталог игр.
3. Через метод addPlayTime добавить одному игроку его игровое время.
4. Повторить п.3 несколько раз
5. Вызвать метод getSumPlayedTime
6. Запустить тест
7. Посмотреть на вывод в консоли

### Скриншот
![скрин](https://monosnap.com/image/BPA44ooG31v9CHcyQK9xG3AWozfhnu)

### Окружение
Операционная система: Windows 10
IDE: IntelliJ IDEA 2022.3.1 (Community Edition)
Java: OpenJDK 11

**Comment by AnaIvy** [comment]
**Fixed** with a commit **"Fix commit"**
