### ISSUE TITLE
Метод sumGenre не вычисляет сумму часов игры одного жанра

### ISSUE THREAD

**Issue by AnaIvy** [Gala05/Team-Project_Game-activity-tracking-#4]
# Описание
Метод **sumGenre** в классе Player не суммирует общее количество часов игры определенного жанра, при наличии одной игры результат метода - 0, при нескольких одного жанра, результат выполнения метода - сумма количества игр, а не количество часов игры одного жанра.

# Локация дефекта
https://github.com/Gala05/Team-Project_Game-activity-tracking-/blob/4a8fc19da2f4f572613c2b21529085f073007992/src/main/java/ru/netology/Player.java#L48

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Gala05/Team-Project_Game-activity-tracking-/blob/player/src/main/java/ru/netology/Player.java) в Idea.
2. Создаем тест, в котором с использованием классов Player и GameStore игрок и каталог.
3. Задать игру(игры) с указанием наименования названия и жанра через метод publishGame.
4. Задать игрока с указанием заданной ранее игры и количеством часов игры через метод play.
5. Вызвать метод sumGenre
6. Запустить тест
7. Посмотреть ответ в консоли

# Скриншот
<img width="1440" alt="Снимок экрана 2023-04-20 в 22 52 35" src="https://user-images.githubusercontent.com/122403121/233473612-e9b208a7-93a4-4f33-8739-b97fead2fb76.png">

# Окружение
- Операционная система: macOS 12.0.1 (21A559)
- IDE: IntelliJ IDEA 2022.3.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Gala05** [comment]
fixed with a commit "fix issues #4 #5 #6 #7"
