### ISSUE TITLE
Метод mostPlayerByGenre не выдает название игры 

### ISSUE THREAD

**Issue by AnaIvy** [Gala05/Team-Project_Game-activity-tracking-#5]
# Описание
Метод  **mostPlayerByGenre** в классе Player в качестве результата во всех тестируемых случаях выдает результат null

# Локация дефекта
https://github.com/Gala05/Team-Project_Game-activity-tracking-/blob/4a8fc19da2f4f572613c2b21529085f073007992/src/main/java/ru/netology/Player.java#L59

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Gala05/Team-Project_Game-activity-tracking-/blob/player/src/main/java/ru/netology/Player.java) в Idea.
2. Создать тест с использованием классов Player и GameStore.
3. Задать игру(игры) с указанием наименования названия и жанра через метод publishGame.
4. Задать игрока с указанием заданной ранее игры и количеством часов игры через метод play.
5. Вызвать метод mostPlayerByGenre
6. Запустить тест
7. Посмотреть ответ в консоли

# Скриншот

<img width="1440" alt="Снимок экрана 2023-04-20 в 23 10 22" src="https://user-images.githubusercontent.com/122403121/233477146-20793575-157e-4e8e-a77f-9358e33aaac4.png">

# Окружение
- Операционная система: macOS 12.0.1 (21A559)
- IDE: IntelliJ IDEA 2022.3.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Gala05** [comment]
fixed with a commit "fix issues #4 #5 #6 #7"
