### ISSUE TITLE
Метод play не выкидывает RuntimeException, если игра не установлена

### ISSUE THREAD

**Issue by AnaIvy** [Gala05/Team-Project_Game-activity-tracking-#6]
# Описание
Метод **play** в классе Player при отсутствии игры в каталоге не предусматривает суперкласс «RuntimeException», что отрицает отображения исключения, которое может возникать при при нормальной работе.

# Локация дефекта
Отсутствует класс NotFoundException

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Gala05/Team-Project_Game-activity-tracking-/blob/player/src/main/java/ru/netology/Player.java) в Idea.
2. Создаем тест, в котором с использованием классов Player и GameStore игрок и каталог.
3. Задать игру(игры) с указанием наименования названия и жанра через метод publishGame.
4. Задать игрока с указанием заданной ранее игры и количеством часов игры через метод play.
5. Запустить тест
6. Посмотреть ответ в консоли

# Скриншот
<img width="1440" alt="Снимок экрана 2023-04-23 в 17 07 57" src="https://user-images.githubusercontent.com/122403121/233844619-6db61eaf-e1e1-428c-a1b2-9cabb8ec6e08.png">

# Окружение
- Операционная система: macOS 12.0.1 (21A559)
- IDE: IntelliJ IDEA 2022.3.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Gala05** [comment]
fixed with a commit "fix issues #4 #5 #6 #7"
