### ISSUE TITLE
 Метод play не суммирует количество часов, проигранных в одну и ту же игру

### ISSUE THREAD

**Issue by AnaIvy** [Gala05/Team-Project_Game-activity-tracking-#7]
# Описание
В классе Player при использовании метода **play** не суммирует количество часов, проигранных в одну и ту же игру из каталога.

# Локация дефекта
https://github.com/Gala05/Team-Project_Game-activity-tracking-/blob/39031c2dead208a5694aa7812b7630a243a0726d/src/main/java/ru/netology/Player.java#L36
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Gala05/Team-Project_Game-activity-tracking-/blob/player/src/main/java/ru/netology/Player.java) в Idea.
2. Создаем тест, в котором с использованием классов Player и GameStore игрок и каталог.
3. Задать игру(игры) с указанием наименования названия и жанра через метод publishGame.
4. Задать игрока с указанием заданной ранее игры и количеством часов игры через метод play.
5. Запустить тест
6. Посмотреть ответ в консоли

# Скриншот
<img width="1238" alt="Снимок экрана 2023-04-23 в 17 46 36" src="https://user-images.githubusercontent.com/122403121/233846661-b79bc643-beeb-46bb-aa3f-3ac68797c28a.png">

# Окружение
- Операционная система: macOS 12.0.1 (21A559)
- IDE: IntelliJ IDEA 2022.3.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Gala05** [comment]
fixed with a commit "fix issues #4 #5 #6 #7"
