### ISSUE TITLE
Метод totalPlayingTimeByPlayer не суммирует время, которое играл конкретный игрок при наличие 2 игр

### ISSUE THREAD

**Issue by AnaIvy** [Gala05/Team-Project_Game-activity-tracking-#8]
# Описание
В классе Player при использовании метода **totalPlayingTimeByPlayer** не суммируется количество часов, проигранных одним и тем же игроком при наличии двух игр. 
# Локация дефекта
https://github.com/Gala05/Team-Project_Game-activity-tracking-/blob/c849e9adb6dfc4bc36af7af48c75d7b81a45aced/src/main/java/ru/netology/Player.java#L78
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Gala05/Team-Project_Game-activity-tracking-/blob/player/src/main/java/ru/netology/Player.java) в Idea.
2. Создать тест, с использованием классов Player и GameStore игрок и каталог.
3. Задать игрока(ов)
4.Опубликовать игры с указанием названия игры и жанра через метод publishGame.
5. С использованием метода installGame добавить игры игроку.
5. Задаем игроку количество часов игры через метод play с указанием заданных ранее игр. 
6. Запуск теста
6. Посмотреть ответ в консоли

# Скриншот
<img width="1440" alt="Снимок экрана 2023-04-26 в 23 41 23" src="https://user-images.githubusercontent.com/122403121/234697654-0b552c86-0a6d-48f2-874f-094385b7a21c.png">

# Окружение
- Операционная система: macOS 12.0.1 (21A559)
- IDE: IntelliJ IDEA 2022.3.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Gala05** [comment]
fixed with a commit "fix issue #8"
